### ISSUE TITLE
keycloak  ERROR: Didn't find publicKey for kid: ERROR: Failed to verify token

### ISSUE THREAD

**Issue by kiat** [hobbit-project/platform#18]
When running docker-compose up 

I get this error: 

```
gui_1                  | Mar 21, 2017 5:34:33 PM org.keycloak.adapters.rotation.AdapterRSATokenVerifier getPublicKey
gui_1                  | ERROR: Didn't find publicKey for kid: II6HXjVjA1f_MonEpzFyqIg17iTqw6637iujJw6g_cQ
gui_1                  | Mar 21, 2017 5:34:33 PM org.keycloak.adapters.BearerTokenRequestAuthenticator authenticateToken
gui_1                  | ERROR: Failed to verify token
gui_1                  | org.keycloak.common.VerificationException: Didn't find publicKey for specified kid
gui_1                  |     at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.getPublicKey(AdapterRSATokenVerifier.java:47)
gui_1                  |     at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:55)
gui_1                  |     at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:37)
gui_1                  |     at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken(BearerTokenRequestAuthenticator.java:87)
gui_1                  |     at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate(BearerTokenRequestAuthenticator.java:82)
gui_1                  |     at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:65)
gui_1                  |     at org.keycloak.adapters.jetty.core.AbstractKeycloakJettyAuthenticator.validateRequest(AbstractKeycloakJettyAuthenticator.java:301)
gui_1                  |     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
gui_1                  |     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
gui_1                  |     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
gui_1                  |     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
gui_1                  |     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
gui_1                  |     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
gui_1                  |     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
gui_1                  |     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
gui_1                  |     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
gui_1                  |     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
gui_1                  |     at org.eclipse.jetty.server.Server.handle(Server.java:534)
gui_1                  |     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
gui_1                  |     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
gui_1                  |     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
gui_1                  |     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
gui_1                  |     at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
gui_1                  |     at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
gui_1                  |     at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
gui_1                  |     at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
gui_1                  |     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
gui_1                  |     at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
gui_1                  |     at java.lang.Thread.run(Thread.java:745)

```

**Comment by MichaelRoeder** [comment]
@romankorf Do you know what causes this problem? We had the same problem on the machine of @kleanthi (Ubuntu OS) and were not able to figure out the reason for that.

**Comment by romankorf** [comment]
One possible reason for the issue might be that the keycloak versions in the Docker file [1] and the one in the pom file [2] are different. While keycloak version 2.3.0 [1] uses public keys the version 2.4.0 [2] does not.

[1] https://github.com/hobbit-project/platform/blob/master/hobbit-gui/gui-serverbackend/Dockerfile 
[2] https://github.com/hobbit-project/platform/blob/master/hobbit-gui/gui-serverbackend/pom.xml

**Comment by MichaelRoeder** [comment]
I applied the changes Roman suggested.

@kiat @Kleanthi could one of you please try the new version and check, whether the problem still persists? Since I can not recreate the problem localy, I can not test it by myself.

**Comment by Kleanthi** [comment]
I will do asap and let you know!

**Comment by Kleanthi** [comment]
I have just finished deploying the platform locally using the GUI and it
seems that the problem is still there.

Best,
Kleanthi

**Comment by romankorf** [comment]
We could not reproduce the issue after the version conflict of keycloak and the keycloak client libraries has been fixed. A possible solution would be to have a clean reinstall.

**Comment by Kleanthi** [comment]
I will try to do this as well. Thank you all for your help.


Kleanthi

**Comment by MichaelRoeder** [comment]
Thanks to Ivan, we figured out the problem. It is a problem in the communication between the GUI server and the keycloak container. While the browser can see (and connect to) both containers, the GUI server is not able to connect to keycloak using the redirect address configured in the `docker-compose.yml`.

## Workaround
Until the open the `hosts` file of your computer and add
```
keycloak 127.0.0.1
```

Adapt the `docker-compose.yml` file in the following way:
```
   gui:
     ...
     ports:
      - "8082:8080"
     ...
     environment:
     - KEYCLOAK_AUTH_URL=http://keycloak:8080/auth
       
   # Keycloak user management (used by the GUI)
   keycloak:
     ...
     ports:
     - "8080:8080"
     networks:
     - hobbit-core
```
Now, keycloak will be deployed on port `8080` and the GUI is deployed on `8082`. These changes have to be reflected in the Keycloak configuration as well. [Start Keycloak and adapt its cofiguration as described in the readme file](https://github.com/hobbit-project/platform#configure-keycloak).

## Solution
The `gui-serverbackend` needs to take two addresses as environmental variable. One for redirecting the user and the other one for directly communicating with it.
@romankorf Could you please have a look at it?

**Comment by romankorf** [comment]
KeyCloak must to be accessed from all clients by the same public address for security reasons. This includes also the GUI server. It is not possible to talk to Keycloak via a local IP address as the security depends on the IP address.

# Allow gui access to external keycloak address
The serverbackend of the hobbitgui container needs access to keycloak via the external IP address.
Therefore you may need to adapt the firewall rules.
First find the IP range of the hobbit network:
```
docker network inspect hobbit | grep Gateway
```
Assuming you get something like "Gateway": "172.19.0.1" you have to find the matching network device:
```
ip addr | grep -B 2 172.19.0
```
If you get something like
```
6: br-5c9d73b080ad: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:22:50:d4:8c brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.1/16 scope global br-5c9d73b080ad
```
the network device name is `br-5c9d73b080ad`

If you have `iptables`as firewall use:
```
iptables -A INPUT -i br-5c9d73b080ad -j ACCEPT
```
If you have `firewalld` (fedora/centos7) use:
```
firewall-cmd --permanent --zone=trusted --change-interface=br-5c9d73b080ad
firewall-cmd --reload

**Comment by MichaelRoeder** [comment]
@romankorf we made sure that the keycloak is configured correctly. The problem still persists (and it also causes #29). Please implement the solution [described above](https://github.com/hobbit-project/platform/issues/18#issuecomment-298050869).

**Comment by MichaelRoeder** [comment]
## Solution

As described above, we changed the UI to use 2 URLs for Keycloak. One URL is used for redirecting the user to Keycloak while the second is used to directly communicate with Keycloak (necessary for verifying the security token received by from a user).

The implemented solution can be found in the [hotfix-twoKeycloakUrls](https://github.com/hobbit-project/platform/tree/hotfix-twoKeycloakUrls) branch. The issue will be closed as soon as it has been merged with the master and released.

### Changes in UI

The UI has 3 parameters that are related to the user authentication.
```yaml
      - KEYCLOAK_AUTH_URL=http://192.168.99.100:8181/auth
      - CHECK_REALM_URL=false
      - KEYCLOAK_DIRECT_URL=http://keycloak:8080/auth
```
`KEYCLOAK_AUTH_URL` is the URL used for redirecting the users browser. `KEYCLOAK_DIRECT_URL` is the URL that is used for communicating with keycloak. In most cases, it will be set to the address above which is the address of the Keycloak service inside the virtual Docker network. `CHECK_REALM_URL` has to be set to `false` as long as the two URLs are different. If they are the same (e.g., this is the case in our online setup), it can be set to `true` increasing the security.

### Jetty plugin

We had to adapt the Keycloak's Jetty plugin. Our extended plugin offers the configuration of the realm check feature using the `CHECK_REALM_URL` variable shown above. It can be found at https://github.com/hobbit-project/keycloak-jetty-adapter-for-hobbit

**Comment by smirnp** [comment]
I have modified the default configuration as described above (Gui on 8082 and Keycloak on 8080) and started to receive cross-origin error (Failed to init user authentication...) on localhost:8082:

```
  # HOBBIT GUI
  gui:
    build: ./hobbit-gui/gui-serverbackend
    ports:
      - "8082:8080"
    networks:
      - hobbit-core
      - hobbit
    depends_on:
      - platform-controller
      - rabbit
      - virtuoso
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - KEYCLOAK_AUTH_URL=http://localhost:8080/auth
      - CHECK_REALM_URL=true
      - KEYCLOAK_DIRECT_URL=http://localhost:8080/auth

  # Keycloak user management (used by the GUI)
  keycloak:
    image: git.project-hobbit.eu:4567/gitadmin/hobbit-keycloak:1.0.0
    container_name: keycloak
    restart: always
    ports:
      - "8080:8080"
    networks:
      - hobbit-core
    volumes:
      - ./config/keycloak:/opt/jboss/keycloak/standalone/data/db
```

Here is my Hobbit-GUI configuration: https://gyazo.com/9e1cf3aa3e9032a1019452b44e5c3b29 

I also added firewall exception. 

Could you please check the configs, may be will find something wrong

**Comment by MichaelRoeder** [comment]
Changing the GUI to 8082 and Keycloak to 8080 shouldn't be necessary, anymore. That is why we closed this issue.

The Keycloak configuration looks good. 

Could you do a step back and give me the original problem that you had which caused you to change the ports?

**Comment by smirnp** [comment]
Here it is:

```
gui_1                  | 2017-11-02 14:52:42,486 INFO [de.usu.research.hobbit.gui.rest.InternalResources] - <Keycloak configuration for webapp: realm=Hobbit, url=http://keycloak:8181/auth, clientId=Hobbit-GUI>
gui_1                  | Nov 02, 2017 2:52:58 PM org.keycloak.adapters.BearerTokenRequestAuthenticator authenticateToken
gui_1                  | ERROR: Failed to verify token
gui_1                  | org.keycloak.common.VerificationException: Invalid token issuer. Expected 'http://keycloak:8080/auth/realms/Hobbit', but was 'http://keycloak:8181/auth/realms/Hobbit'
gui_1                  |        at org.keycloak.RSATokenVerifier.verify(RSATokenVerifier.java:140)
gui_1                  |        at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:80)
gui_1                  |        at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:43)
gui_1                  |        at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken(BearerTokenRequestAuthenticator.java:87)
gui_1                  |        at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate(BearerTokenRequestAuthenticator.java:82)
gui_1                  |        at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:65)
gui_1                  |        at org.keycloak.adapters.jetty.core.AbstractKeycloakJettyAuthenticator.validateRequest(AbstractKeycloakJettyAuthenticator.java:301)
gui_1                  |        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
gui_1                  |        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
gui_1                  |        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
gui_1                  |        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
gui_1                  |        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
gui_1                  |        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
gui_1                  |        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
gui_1                  |        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
gui_1                  |        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
gui_1                  |        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
gui_1                  |        at org.eclipse.jetty.server.Server.handle(Server.java:534)
gui_1                  |        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
gui_1                  |        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
gui_1                  |        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
gui_1                  |        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
gui_1                  |        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
gui_1                  |        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
gui_1                  |        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
gui_1                  |        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
gui_1                  |        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
gui_1                  |        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
gui_1                  |        at java.lang.Thread.run(Thread.java:748)
```

**Comment by MichaelRoeder** [comment]
Yes, because there is something wrong :confused: 
The token has been created by `http://keycloak:8181/auth` but your UI is obviously asking `http://keycloak:8080/auth` to verify the token. The UI won't accept this as long as you don't set CHECK_REALM_URL to `false`

However, I still do not understand why you started to change the ports in the first place. Typically, this shouldn't be a problem anymore. The default configuration should already work.

**Comment by romankorf** [comment]
Hi, looks like the keykloak host name `localhost` is the issue here.

```
#HOBBIT GUI
  gui:
    ...
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - KEYCLOAK_AUTH_URL=http://localhost:8080/auth
      - CHECK_REALM_URL=true
      - KEYCLOAK_DIRECT_URL=http://localhost:8080/auth
```
It should be a name of the keycloak host or the IP address it can be accessed at from the browser you use for HOBBIT platform.

**Comment by smirnp** [comment]
Sorry, that was my fault. 
Specifying CHECK_REALM_URL=false helped to solve it.
